name: New member
description: Become a Django Commons member with the following form.
labels: ["New member"]
title: "✋ [MEMBER] - your_username_here"
assignees: 'django-commons/admins'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for expressing interest in joining Django Commons! Once approved, you'll receive an email invitation to join. Once you receive that email you'll have 7 days to accept.
  - type: textarea
    id: why-join
    attributes:
      label: Why do you want to join?
      description: We're looking to confirm that you're a human. Keep it to 2-4 sentences.
      placeholder: Keep it to 2-4 sentences.
    validations:
      required: true
  - type: textarea
    id: which-projects
    attributes:
      label: Which project(s) are you looking to contribute to?
    validations:
      required: false
  - type: checkboxes
    id: general
    attributes:
      label: General questions
      options:
        - label: Do you wish to join the designers team?
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/django-commons/membership/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Django Commons's Code of Conduct
          required: true

