name: New member
description: Become a Django Commons member with the following form.
labels: ["New member"]
title: "✋ [MEMBER] - <your handle>"
assignees: 'django-commons/admins'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for expressing interest in joining Django Commons!
  - type: textarea
    id: why-join
    attributes:
      label: Why do you want to join?
      description: We're looking to confirm that you're a human. Keep it to 2-4 sentences.
      placeholder: Keep it to 2-4 sentences.
    validations:
      required: true
  - type: textarea
    id: which-projects
    attributes:
      label: Which project(s) are you looking to contribute to?
    validations:
      required: false
  - type: checkboxes
    id: tangible-benefits
    attributes:
      label: Tangible Benefits
      options:
        - label: Does your project provide tangible benefits to the Django community?
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/django-commons/membership/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Django Commons's Code of Conduct
          required: true

