name: Transfer project in
description: Transfer a project into Django commons with the following form.
labels: ["Transfer project in"]
title: "🛬 [INBOUND] - <project>"
assignees: 'django-commons/admins'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for expressing interesting in adding your project to Django Commons!

        Please review the [incoming repository requirements](https://github.com/django-commons/membership/blob/main/incoming_repo_requirements.md) before submitting your request.
  - type: input
    id: project-url
    attributes:
      label: What's the URL to the project?
      placeholder: "https://github.com/django-commons/django-commons-playground"
    validations:
      required: true
  - type: input
    id: current-maintainer
    attributes:
      label: Who are the current maintainers?
    validations:
      required: true
  - type: checkboxes
    id: tests
    attributes:
      label: Does the project have the required attributes?
      description: "[Review the incoming repo requirements for details.](https://github.com/django-commons/membership/blob/main/incoming_repo_requirements.md)"
      options:
        - label: Does the project have tests?
        - label: Does the project have documentation?
        - label: Has the project adopted [Django Commons's Code of Conduct](https://github.com/django-commons/membership/blob/main/CODE_OF_CONDUCT.md)?
  - type: textarea
    id: new-maintainers
    attributes:
      label: Who will be the new maintainers of the project?
    validations:
      required: false
  - type: checkboxes
    id: options
    attributes:
      label: Which of the following options would you like?
      description: "These are entirely up to you and can be changed at a later time."
      options:
        - label: Does the project have a test.pypi.org project?
        - label: Would you like to test your deployments with uploads to test.pypi.org (you'll need to create the project first)?
        - label: Would you like to use GitHub's merge commits?
        - label: Would you like to use GitHub's rebase and merge?
        - label: Would you like to use GitHub's squash and merge?
        - label: Would you like to use GitHub's Discussions?
        - label: Would you like to use GitHub's Wiki?
